### PR TITLE
Add progress bars for downloading

### LINKED ISSUE #60: Feature: Add progress bar during download
Optionally behind a `verbose` parameter, but it'd be nice in some cases for the user to be aware that downloads are happening in the background.

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #60

- [x] `urllib` support (inspired by https://gist.github.com/leimao/37ff6e990b3226c2c9670a2cd1e4a6f5)
- [x] `requests` support (inspired by https://stackoverflow.com/a/63831344/5775947)

Example usage:

```python
import pystow

if __name__ == '__main__':
    url = "https://zenodo.org/record/7633479/files/emojis.zip?download=1"
    path = pystow.ensure(
        "test",
        force=True,
        url=url,
        name="emojis.zip",
        download_kwargs=dict(progress_bar=True, backend="requests", tqdm_kwargs=dict(leave=True)),
    )
    print("download succeeded to ", path)
```

### CODE REVIEW

**Comment by cthoyt** [comment]
Hi @sgbaird @glass-ships, could you please test this out and let me know what you think?

**Comment by glass-ships** [comment]
will do, thanks @cthoyt !!

**Comment by glass-ships** [comment]
Hmm, I don't notice any change in behavior.  
Is it because I'm using methods like `ensure_open_sqlite_gz()`? 
(Does `download()` get called by these other ensure methods / could it be implemented?)

**Comment by cthoyt** [comment]
This behavior isn't enabled by default, you'll have to do something like:

```python
import pystow

if __name__ == '__main__':
    url = "https://zenodo.org/record/7633479/files/emojis.zip?download=1"
    path = pystow.ensure(
        "test",
        force=True,
        url=url,
        name="emojis.zip",
        download_kwargs=dict(progress_bar=True, backend="requests", tqdm_kwargs=dict(leave=True)),
    )
    print("download succeeded to ", path)
```

**Comment by glass-ships** [comment]
> This behavior isn't enabled by default, you'll have to do something like:
> 
> ```python
> import pystow
> 
> if __name__ == '__main__':
>     url = "https://zenodo.org/record/7633479/files/emojis.zip?download=1"
>     path = pystow.ensure(
>         "test",
>         force=True,
>         url=url,
>         name="emojis.zip",
>         download_kwargs=dict(progress_bar=True, backend="requests", tqdm_kwargs=dict(leave=True)),
>     )
>     print("download succeeded to ", path)
> ```

Hmmm, still no luck. Sorry I think I'm missing something here. 
Updated the call to: 
```python
with monarchstow.ensure_open_sqlite_gz(
    "sql", 
    url=SQL_DATA_URL, 
    force=update, 
    download_kwargs=dict(progress_bar=True
    )
```
But I'm getting `TypeError: urlretrieve() got an unexpected keyword argument 'progress_bar'` or `TypeError: Session.request() got an unexpected keyword argument 'progress_bar'`

<details>
    <summary>Full traceback</summary>

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\dev\tislab\monarch-py\src\monarch_py\sql_cli.py:20 in entity                                  │
│                                                                                                  │
│   17 │   │   update (bool): = Whether to re-download the Monarch KG. Default False               │
│   18 │   """                                                                                     │
│   19 │   data = SQLImplementation()                                                              │
│ ❱ 20 │   entity = data.get_entity(id, update)                                                    │
│   21 │   if not entity:                                                                          │
│   22 │   │   print(f"\nEntity '{id}' not found.\n")                                              │
│   23 │   │   typer.Abort()                                                                       │
│                                                                                                  │
│ ╭───────── locals ─────────╮                                                                     │
│ │   data = <class          │                                                                     │
│ │          'rich.pretty.N… │                                                                     │
│ │          returned empty  │                                                                     │
│ │          string          │                                                                     │
│ │     id = 'MONDO:0012933' │                                                                     │
│ │ update = False           │                                                                     │
│ ╰──────────────────────────╯                                                                     │
│                                                                                                  │
│ D:\dev\tislab\monarch-py\src\monarch_py\implementations\sql\sql_implementation.py:42 in          │
│ get_entity                                                                                       │
│                                                                                                  │
│    39 │   │   if not any(Path(monarchstow.base).iterdir()):                                      │
│    40 │   │   │   print("\nDownloading Monarch SQL KG...\n")                                     │
│    41 │   │                                                                                      │
│ ❱  42 │   │   with monarchstow.ensure_open_sqlite_gz(                                            │
│    43 │   │   │   │   "sql",                                                                     │
│    44 │   │   │   │   url=SQL_DATA_URL,                                                          │
│    45 │   │   │   │   force=update,                                                              │
│                                                                                                  │
│ ╭───────── locals ─────────╮                                                                     │
│ │     id = 'MONDO:0012933' │                                                                     │
│ │   self = <class          │                                                                     │
│ │          'rich.pretty.N… │                                                                     │
│ │          returned empty  │                                                                     │
│ │          string          │                                                                     │
│ │ update = False           │                                                                     │
│ ╰──────────────────────────╯                                                                     │
│                                                                                                  │
│ D:\dev\python310\lib\contextlib.py:135 in __enter__                                              │
│                                                                                                  │
│   132 │   │   # they are only needed for recreation, which is not possible anymore               │
│   133 │   │   del self.args, self.kwds, self.func                                                │
│   134 │   │   try:                                                                               │
│ ❱ 135 │   │   │   return next(self.gen)                                                          │
│   136 │   │   except StopIteration:                                                              │
│   137 │   │   │   raise RuntimeError("generator didn't yield") from None                         │
│   138                                                                                            │
│                                                                                                  │
│ ╭───────────────────────────────── locals ──────────────────────────────────╮                    │
│ │ self = <contextlib._GeneratorContextManager object at 0x000001F58E55D8A0> │                    │
│ ╰───────────────────────────────────────────────────────────────────────────╯                    │
│                                                                                                  │
│ D:\dev\tislab\monarch-py\.venv\lib\site-packages\pystow\impl.py:1485 in ensure_open_sqlite_gz    │
│                                                                                                  │
│   1482 │   │   """                                                                               │
│   1483 │   │   import sqlite3                                                                    │
│   1484 │   │                                                                                     │
│ ❱ 1485 │   │   path = self.ensure_gunzip(                                                        │
│   1486 │   │   │   *subkeys, url=url, name=name, force=force, download_kwargs=download_kwargs    │
│   1487 │   │   )                                                                                 │
│   1488 │   │   with closing(sqlite3.connect(path.as_posix())) as conn:                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ download_kwargs = {                                                                          │ │
│ │                   │   'progress_bar': True,                                                  │ │
│ │                   │   'backend': 'requests',                                                 │ │
│ │                   │   'tqdm_kwargs': {'leave': True}                                         │ │
│ │                   }                                                                          │ │
│ │           force = False                                                                      │ │
│ │            name = None                                                                       │ │
│ │            self = <pystow.impl.Module object at 0x000001F58E52DB10>                          │ │
│ │         sqlite3 = <module 'sqlite3' from 'D:\\dev\\python310\\lib\\sqlite3\\__init__.py'>    │ │
│ │         subkeys = ('sql',)                                                                   │ │
│ │             url = 'https://data.monarchinitiative.org/monarch-kg-dev/latest/monarch-kg.db.g… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\dev\tislab\monarch-py\.venv\lib\site-packages\pystow\impl.py:297 in ensure_gunzip             │
│                                                                                                  │
│    294 │   │   gunzipped_path = self.join(*subkeys, name=gunzipped_name, ensure_exists=True)     │
│    295 │   │   if gunzipped_path.is_file() and not force:                                        │
│    296 │   │   │   return gunzipped_path                                                         │
│ ❱  297 │   │   path = self.ensure(                                                               │
│    298 │   │   │   *subkeys,                                                                     │
│    299 │   │   │   url=url,                                                                      │
│    300 │   │   │   name=name,                                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       autoclean = True                                                                       │ │
│ │ download_kwargs = {                                                                          │ │
│ │                   │   'progress_bar': True,                                                  │ │
│ │                   │   'backend': 'requests',                                                 │ │
│ │                   │   'tqdm_kwargs': {'leave': True}                                         │ │
│ │                   }                                                                          │ │
│ │           force = False                                                                      │ │
│ │  gunzipped_name = 'monarch-kg.db'                                                            │ │
│ │  gunzipped_path = WindowsPath('C:/Users/glass/.data/monarch/sql/monarch-kg.db')              │ │
│ │            name = 'monarch-kg.db.gz'                                                         │ │
│ │            self = <pystow.impl.Module object at 0x000001F58E52DB10>                          │ │
│ │         subkeys = ('sql',)                                                                   │ │
│ │             url = 'https://data.monarchinitiative.org/monarch-kg-dev/latest/monarch-kg.db.g… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\dev\tislab\monarch-py\.venv\lib\site-packages\pystow\impl.py:171 in ensure                    │
│                                                                                                  │
│    168 │   │   if name is None:                                                                  │
│    169 │   │   │   name = name_from_url(url)                                                     │
│    170 │   │   path = self.join(*subkeys, name=name, ensure_exists=True)                         │
│ ❱  171 │   │   utils.download(                                                                   │
│    172 │   │   │   url=url,                                                                      │
│    173 │   │   │   path=path,                                                                    │
│    174 │   │   │   force=force,                                                                  │
│ │ params = None                                                                        │         │
│ │    url = 'https://data.monarchinitiative.org/monarch-kg-dev/latest/monarch-kg.db.gz' │         │
│ ╰──────────────────────────────────────────────────────────────────────────────────────╯         │
│                                                                                                  │
│ D:\dev\tislab\monarch-py\.venv\lib\site-packages\requests\api.py:59 in request                   │
│                                                                                                  │
│    56 │   # avoid leaving sockets open which can trigger a ResourceWarning in some               │
│    57 │   # cases, and look like a memory leak in others.                                        │
│    58 │   with sessions.Session() as session:                                                    │
│ ❱  59 │   │   return session.request(method=method, url=url, **kwargs)                           │
│    60                                                                                            │
│    61                                                                                            │
│    62 def get(url, params=None, **kwargs):                                                       │
│                                                                                                  │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮        │
│ │  kwargs = {                                                                           │        │
│ │           │   'params': None,                                                         │        │
│ │           │   'progress_bar': True,                                                   │        │
│ │           │   'tqdm_kwargs': {'leave': True},                                         │        │
│ │           │   'stream': True                                                          │        │
│ │           }                                                                           │        │
│ │  method = 'get'                                                                       │        │
│ │ session = <requests.sessions.Session object at 0x000001F58E55DA20>                    │        │
│ │     url = 'https://data.monarchinitiative.org/monarch-kg-dev/latest/monarch-kg.db.gz' │        │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

</details>

**Comment by cthoyt** [comment]
@glass-ships you'll have to install your code from the branch where I implemented this, since it's neither merged nor released

**Comment by glass-ships** [comment]
> @glass-ships you'll have to install your code from the branch where I implemented this, since it's neither merged nor released

I thought I had done exactly that by issuing the following: 
```bash
$ poetry run pip uninstall pystow 
$ cd </pystow/path> 
$ poetry -C </my/library/path> run pip install . 
```

A `pip freeze | grep 'pystow'` returns `pystow @ file:///D:/dev/pystow` though, which I guess I expected to be the version num..

Apologies for my stumbling around, I'm still getting used to manually managing dependencies with Poetry.

**Comment by glass-ships** [comment]
Ok, sorry again, looks like I've sorted my issue - my system appeared to be caching an older version and claiming it was up to date! 

I nuked my environment and started again, and everything appears kosher! 

```bash
(monarch-py-py3.10) PS D:\dev\pystow> monarch sql entity --id MONDO:0012933
Downloading monarch-kg.db.gz: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 475M/475M [00:04<00:00, 110MB/s]
{
    "id": "MONDO:0012933",
    "category": [
        "biolink:Disease"
    ],
    "name": "breast-ovarian cancer, familial, susceptibility to, 2",
    "description": "Any hereditary breast ovarian cancer syndrome in which the cause of the disease is a mutation in the BRCA2 gene.",
    "xref": [
        ""
    ],
    "provided_by": "phenio_nodes",
    "in_taxon": null,
    "source": null,
    "symbol": null,
    "type": null,
    "synonym": [
        ""
    ]
}
```

**Comment by cthoyt** [comment]
FYI @glass-ships I have made a release 0.5.0 that includes this feature

**Pull request merged**
